"""Delivery: patch generation and Draft PR guard (spec §5, §4.4).

M5 produces a Patch artifact; a Draft PR may only be prepared for test
repositories (the actual GitHub submission is M6 infrastructure).
"""

from __future__ import annotations

from collections.abc import Collection
from dataclasses import dataclass
from datetime import UTC, datetime

from forgeflow.errors import ForgeFlowError


@dataclass(frozen=True)
class Patch:
    repository: str
    diff: str
    changed_files: list[str]
    generated_at: str


@dataclass(frozen=True)
class DraftPr:
    repository: str
    title: str
    body: str
    changed_files: list[str]


class DraftPrGuardError(ForgeFlowError):
    """A Draft PR was requested for a repository that is not a test repository."""


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


def make_patch(*, repository: str, diff: str, changed_files: list[str]) -> Patch:
    return Patch(
        repository=repository,
        diff=diff,
        changed_files=list(changed_files),
        generated_at=_now_iso(),
    )


class DeliveryService:
    """Prepares delivery artifacts; Draft PRs are only allowed for test repos."""

    def __init__(self, test_repositories: Collection[str]) -> None:
        self._test_repositories = set(test_repositories)

    def create_draft_pr(self, *, repository: str, patch: Patch) -> DraftPr:
        if repository not in self._test_repositories:
            raise DraftPrGuardError(
                f"Draft PR 只允许测试仓库：{repository} 不在 {sorted(self._test_repositories)}"
            )
        first_file = patch.changed_files[0] if patch.changed_files else "change"
        return DraftPr(
            repository=repository,
            title=f"feat: {first_file}",
            body=f"Patch generated by ForgeFlow.\n\n```diff\n{patch.diff}\n```",
            changed_files=list(patch.changed_files),
        )
