"""Delivery: patch generation and Draft PR submission (spec §5, §4.4; PHASE3 B1).

M5 produces a Patch artifact.  For test repositories a Draft PR is prepared
locally (Draft semantics, no remote).  When a ``GitHubPrClient`` is configured,
real repositories get an actual Draft PR on GitHub via the gh CLI — the guard
only rejects real repositories when no GitHub client is available.
"""

from __future__ import annotations

from collections.abc import Collection
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from forgeflow.errors import ForgeFlowError

if TYPE_CHECKING:
    from forgeflow.infrastructure.github import GitHubPrClient


@dataclass(frozen=True)
class Patch:
    repository: str
    diff: str
    changed_files: list[str]
    generated_at: str


@dataclass(frozen=True)
class DraftPr:
    repository: str
    title: str
    body: str
    changed_files: list[str]
    url: str | None = None
    number: str = ""


class DraftPrGuardError(ForgeFlowError):
    """A Draft PR was requested for a repository that is not a test repository."""


class DraftPrRemoteError(ForgeFlowError):
    """A real Draft PR could not be created for a real repository."""


def _now_iso() -> str:
    return datetime.now(UTC).isoformat()


def make_patch(*, repository: str, diff: str, changed_files: list[str]) -> Patch:
    return Patch(
        repository=repository,
        diff=diff,
        changed_files=list(changed_files),
        generated_at=_now_iso(),
    )


class DeliveryService:
    """Prepares delivery artifacts; real Draft PRs require a GitHub client."""

    def __init__(
        self,
        test_repositories: Collection[str],
        github: GitHubPrClient | None = None,
    ) -> None:
        self._test_repositories = set(test_repositories)
        self._github = github

    def create_draft_pr(
        self,
        *,
        repository: str,
        patch: Patch,
        base: str = "main",
        head: str = "",
    ) -> DraftPr:
        """Create a Draft PR: locally for test repos, on GitHub for real repos."""
        first_file = patch.changed_files[0] if patch.changed_files else "change"
        title = f"feat: {first_file}"
        body = f"Patch generated by ForgeFlow.\n\n```diff\n{patch.diff}\n```"
        if repository in self._test_repositories:
            return DraftPr(
                repository=repository,
                title=title,
                body=body,
                changed_files=list(patch.changed_files),
            )
        if self._github is None:
            raise DraftPrGuardError(
                f"Draft PR 只允许测试仓库：{repository} 不在 {sorted(self._test_repositories)}"
            )
        if not head:
            raise DraftPrRemoteError(
                f"real Draft PR for {repository} requires a head branch (got '')"
            )
        try:
            info = self._github.create_draft_pr(
                title=title,
                body=body,
                base=base,
                head=head,
                repository=repository,
            )
        except Exception as exc:
            raise DraftPrRemoteError(
                f"real Draft PR for {repository} failed: {exc}"
            ) from exc
        return DraftPr(
            repository=repository,
            title=title,
            body=body,
            changed_files=list(patch.changed_files),
            url=info.url,
            number=info.number,
        )
